<script setup lang="ts">
const email = ref(''); const password = ref(''); const error = ref(''); const pending = ref(false)
const hydrated = ref(false)
const resetOpen = ref(false); const resetEmail = ref(''); const resetNotice = ref(''); const resetPending = ref(false)
onMounted(() => { hydrated.value = true })
async function login() { pending.value = true; error.value = ''; try { await $fetch('/api/auth/login', { method: 'POST', body: { email: email.value, password: password.value } }); await useUserSession().fetch(); await navigateTo('/') } catch (cause: any) { error.value = cause?.data?.statusMessage ?? 'Не удалось войти. Проверьте email и пароль.' } finally { pending.value = false } }
async function resetPassword() { resetPending.value = true; resetNotice.value = ''; try { await $fetch('/api/auth/request-password-reset', { method: 'POST', body: { email: resetEmail.value } }); resetNotice.value = 'Если аккаунт существует, ссылка отправлена на почту.' } finally { resetPending.value = false } }
</script>
<template><div class="w-full max-w-md"><NuxtLink to="/login" class="brand-mark mb-10 text-2xl lg:hidden">aparts<span>.</span></NuxtLink><div class="surface p-6 sm:p-8"><h2 class="text-3xl font-semibold tracking-[-.045em]">Добро пожаловать</h2><p class="mt-2 text-sm leading-6 text-[var(--color-muted)]">Войдите в рабочее пространство Aparts CRM.</p><form class="mt-7 space-y-5" @submit.prevent="login"><UFormField label="Email"><UInput v-model="email" type="email" autocomplete="email" placeholder="name@example.com" class="w-full" required /></UFormField><UFormField label="Пароль"><UInput v-model="password" type="password" autocomplete="current-password" placeholder="Ваш пароль" class="w-full" required /></UFormField><UAlert v-if="error" color="error" variant="soft" icon="i-lucide-circle-alert" :description="error" /><UButton type="submit" block size="lg" :loading="pending" :disabled="!hydrated">Войти</UButton></form><button type="button" class="mt-4 min-h-11 w-full text-sm font-semibold text-[var(--color-primary)]" @click="resetOpen = true">Забыли пароль?</button></div><p class="mt-5 text-center text-xs text-[var(--color-muted)]">Доступ выдаёт администратор управляющей компании.</p><UModal v-model:open="resetOpen" title="Восстановление пароля" description="Укажите email, использованный при приглашении."><template #body><form class="form-grid" @submit.prevent="resetPassword"><UFormField label="Email"><UInput v-model="resetEmail" type="email" autocomplete="email" class="w-full" required /></UFormField><UAlert v-if="resetNotice" color="success" variant="soft" :description="resetNotice" /><div class="form-actions"><UButton color="neutral" variant="ghost" @click="resetOpen = false">Отмена</UButton><UButton type="submit" :loading="resetPending">Отправить ссылку</UButton></div></form></template></UModal></div></template>
