<script setup lang="ts">
const email = ref(''); const password = ref(''); const error = ref(''); const pending = ref(false)
const { t, setLocale } = useI18n()
const route = useRoute()
const hydrated = ref(false)
const resetOpen = ref(false); const resetEmail = ref(''); const resetNotice = ref(''); const resetPending = ref(false)
onMounted(() => { hydrated.value = true; const requested = route.query.lang; if (requested === 'ru' || requested === 'en' || requested === 'he') void setLocale(requested) })
async function login() { pending.value = true; error.value = ''; try { await $fetch('/api/auth/login', { method: 'POST', body: { email: email.value, password: password.value } }); await useUserSession().fetch(); await navigateTo('/') } catch (cause: any) { error.value = cause?.data?.statusMessage ?? t('auth.loginError') } finally { pending.value = false } }
async function resetPassword() { resetPending.value = true; resetNotice.value = ''; try { await $fetch('/api/auth/request-password-reset', { method: 'POST', body: { email: resetEmail.value } }); resetNotice.value = t('auth.resetSent') } finally { resetPending.value = false } }
</script>
<template><div class="w-full max-w-md"><NuxtLink to="/login" class="brand-mark mb-10 text-2xl lg:hidden">aparts<span>.</span></NuxtLink><div class="surface p-6 sm:p-8"><h2 class="text-3xl font-semibold tracking-[-.045em]">{{ $t('auth.welcome') }}</h2><p class="mt-2 text-sm leading-6 text-[var(--color-muted)]">{{ $t('auth.loginText') }}</p><form class="mt-7 space-y-5" @submit.prevent="login"><UFormField :label="$t('auth.email')"><UInput v-model="email" type="email" autocomplete="email" placeholder="name@example.com" class="w-full" required /></UFormField><UFormField :label="$t('auth.password')"><UInput v-model="password" type="password" autocomplete="current-password" placeholder="••••••••" class="w-full" required /></UFormField><UAlert v-if="error" color="error" variant="soft" icon="i-lucide-circle-alert" :description="error" /><UButton type="submit" block size="lg" :loading="pending" :disabled="!hydrated">{{ $t('auth.login') }}</UButton></form><button type="button" class="mt-4 min-h-11 w-full text-sm font-semibold text-[var(--color-primary)]" @click="resetOpen = true">{{ $t('auth.forgotPassword') }}</button></div><p class="mt-5 text-center text-xs text-[var(--color-muted)]">{{ $t('auth.accessNote') }}</p><UModal v-model:open="resetOpen" :title="$t('auth.resetTitle')" :description="$t('auth.resetDescription')"><template #body><form id="password-reset-form" class="form-grid" @submit.prevent="resetPassword"><UFormField :label="$t('auth.email')"><UInput v-model="resetEmail" type="email" autocomplete="email" class="w-full" required /></UFormField><UAlert v-if="resetNotice" color="success" variant="soft" :description="resetNotice" /></form></template><template #footer><div class="form-actions form-actions--footer"><UButton type="button" color="neutral" variant="ghost" @click="resetOpen = false">{{ $t('common.cancel') }}</UButton><UButton type="submit" form="password-reset-form" :loading="resetPending">{{ $t('auth.sendLink') }}</UButton></div></template></UModal></div></template>
