import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { cleaningLinenUpdateSchema, userRoleSchema } from '../shared/contracts/crm'
import { canAccessAssignedWork, canAccessWorkSection, type Actor } from '../server/infrastructure/auth/actor'
import { canBeCleaningAssignee, canBeWorkAssignee } from '../server/modules/work/work-policy'

const actor = (roles: Actor['roles']): Actor => ({ id: 'user-1', organizationId: 'organization-1', email: 'user@example.com', name: 'User', roles, locale: 'ru' })

describe('specialist and linen collection', () => {
  it('adds a specialist role and keeps new invitation payloads single-role', () => {
    expect(userRoleSchema.parse('specialist')).toBe('specialist')
    expect(readFileSync('server/api/users/invite.post.ts', 'utf8')).toContain(".length(1)")
  })

  it('allows specialists to work only on assigned tasks, never to clean', () => {
    const specialist = actor(['specialist'])
    expect(canAccessWorkSection(specialist)).toBe(true)
    expect(canAccessAssignedWork(specialist, specialist.id)).toBe(true)
    expect(canAccessAssignedWork(specialist, 'another-user')).toBe(false)
    expect(canBeWorkAssignee(['specialist'])).toBe(true)
    expect(canBeCleaningAssignee(['specialist'])).toBe(false)
  })

  it('lists specialists as assignees for ordinary and problem tasks', () => {
    const work = readFileSync('src/pages/work/WorkPage.vue', 'utf8')
    const problems = readFileSync('src/pages/problems/ProblemsPage.vue', 'utf8')
    const problemService = readFileSync('server/modules/problem/problem.service.ts', 'utf8')
    expect(work).toContain("['cleaner', 'specialist', 'administrator'].includes(role)")
    expect(problems).toContain("member.roles.includes('specialist')")
    expect(problems).toContain("label: t('roles.specialist'), value: '__specialists__'")
    expect(problemService).toContain('активным исполнителем, специалистом или администратором')
  })

  it('accepts only the isolated linen update payload', () => {
    expect(cleaningLinenUpdateSchema.parse({ collected: true })).toEqual({ collected: true })
    expect(cleaningLinenUpdateSchema.safeParse({ collected: false, status: 'completed' }).success).toBe(false)
  })

  it('keeps automated linen collection on the first actual cleaning start', () => {
    const service = readFileSync('server/modules/cleaning/cleaning.service.ts', 'utf8')
    const realtime = readFileSync('src/shared/realtime/model/cleaning-realtime.ts', 'utf8')
    expect(service).toContain('automaticLinenCollection')
    expect(service).toContain("linenCollected: cleaning.apartment.automaticLinenCollection ? true : cleaning.linenCollected")
    expect(service).toContain("publishCleaningChangeForId(actor, cleaningId, 'linen')")
    expect(realtime).toContain("| 'linen'")
  })

  it('keeps specialist data operational and renders linen controls by role', () => {
    const service = readFileSync('server/modules/cleaning/cleaning.service.ts', 'utf8')
    const work = readFileSync('src/pages/work/WorkPage.vue', 'utf8')
    const detail = readFileSync('src/features/work-detail/ui/WorkDetailPage.vue', 'utf8')
    const progress = readFileSync('src/features/work-progress/ui/WorkProgressForm.vue', 'utf8')
    const linenControl = readFileSync('src/entities/cleaning/ui/LinenStatusControl.vue', 'utf8')
    const styles = readFileSync('src/app/styles/main.css', 'utf8')
    expect(service).toContain("if (actor.roles.includes('specialist')) return all.map")
    expect(service).toContain('linenCollected: cleaning.linenCollected')
    expect(work).toContain('(cleanings.value ?? []).filter(canCollectLinen)')
    expect(work).toContain("return isSpecialist.value && ['in_progress', 'completed'].includes(cleaning.status) && !cleaning.linenCollected")
    expect(work).toContain('<LinenStatusControl v-if="isAdministrator || isSpecialist"')
    expect(work).toContain(':editable="canCollectLinen(cleaning)"')
    expect(work).toContain('v-if="!isSpecialist && shouldShowCleaningStatus(cleaning)"')
    expect(work).toContain('v-if="!isSpecialist && cleaningMenuItems(cleaning).length"')
    expect(work).toContain("'work-route-cleaning-row--specialist': isSpecialist")
    expect(work).toContain('class="work-cleaning-status-dot"')
    expect(work).toContain(":data-tone=\"statusTones[cleaning.status] ?? 'neutral'\"")
    expect(work).toContain('v-if="!isSpecialist" class="truncate text-sm text-[var(--color-muted)]"')
    expect(work).toContain('v-else class="hidden truncate text-sm text-[var(--color-muted)] sm:block"')
    expect(work).toContain("v-if=\"isAdministrator\"\n            :variant=\"planningMode === 'cleaners'")
    expect(detail).toContain('#after-checklist')
    expect(detail).toContain('<section class="progress-section">\n            <UCheckbox :model-value="cleaning?.linenCollected"')
    expect(detail).toContain(':show-checklist="!isSpecialist"')
    expect(progress).toContain('</section>\n\n    <slot name="after-checklist" />')
    expect(progress).toContain('<section v-if="showChecklist" class="progress-section"')
    expect(detail).toContain("cleaning.value && !isSpecialist.value && ['assigned', 'in_progress'].includes(cleaning.value.status)")
    expect(detail).toContain("? !isSpecialist.value && work.value.status === 'in_progress'")
    expect(detail).toContain('cleaning?.tariffSnapshot?.ownerTotalEur')
    expect(detail).toContain('cleaning?.tariffSnapshot?.cleanerPoolEur')
    expect(linenControl).toContain('class="linen-status-button h-6 min-h-6 px-2"')
    expect(linenControl).toContain('v-if="editable"')
    expect(linenControl).not.toContain('v-if="startedAt && editable"')
    expect(linenControl).toContain('v-else-if="startedAt || collected"')
    expect(linenControl).toContain(":class=\"collected ? 'text-success' : 'text-error'\"")
    expect(styles).toContain('.work-cleaning-row__linen:has(.linen-status-button) {')
    expect(styles).toContain('.work-cleaning-status-dot[data-tone="success"] {')
    expect(styles).toContain('.work-cleaning-status-dot[data-tone="warning"] {')
    expect(styles).toContain('.work-cleaning-status-dot[data-tone="info"] {')
    expect(styles).toMatch(/\.work-cleaning-status-dot\[data-tone="success"\] \{\s+background-color: #e7f6ef;/)
    expect(styles).toMatch(/\.work-cleaning-status-dot\[data-tone="warning"\] \{\s+background-color: #fff4d7;/)
    expect(styles).toMatch(/\.work-cleaning-status-dot\[data-tone="info"\] \{\s+background-color: #e8f1f7;/)
    expect(styles).not.toContain('margin-inline-start: 0.25rem;')
  })

  it('labels a specialist correctly and excludes bookings from their interface and API', () => {
    const shell = readFileSync('src/app/ui/AppShell.vue', 'utf8')
    const dashboard = readFileSync('src/pages/dashboard/DashboardPage.vue', 'utf8')
    const specialistTasksPage = readFileSync('app/pages/tasks/index.vue', 'utf8')
    const specialistHome = readFileSync('app/middleware/manager-home.ts', 'utf8')
    const stays = readFileSync('server/modules/stay/stay.service.ts', 'utf8')
    const calendarAccess = readFileSync('app/middleware/calendar-access.ts', 'utf8')
    expect(shell).toContain('t("roles.specialist")')
    expect(shell).toContain('const specialistWork = computed<NavItem[]>(() => [')
    expect(shell).toContain('{ to: "/tasks", label: t("work.tasks"), icon: "i-lucide-clipboard-check" }')
    expect(shell).toContain('if (isSpecialistNavigation.value) return specialistWork.value')
    expect(shell).toContain('v-if="!isSpecialistNavigation && (mobileMore.length || user)"')
    expect(shell).toContain('v-if="isSpecialistNavigation"')
    expect(specialistTasksPage).toContain('<WorkPage />')
    expect(specialistHome).toContain("roles.includes('specialist') && !user.value.roles.includes('administrator')")
    expect(specialistHome).toContain("navigateTo('/work')")
    expect(dashboard).toContain('const isSpecialist = computed')
    expect(dashboard).toContain("isWorkerView.value ? Promise.resolve([]) : $fetch<Stay[]>('/api/stays')")
    expect(stays).toContain("requireRole(actor, 'administrator', 'manager')")
    expect(calendarAccess).toContain("navigateTo(canAccessWorkSection(user.value) ? '/work' : '/')")
  })

  it('separates specialist cleanings and tasks into standalone sections', () => {
    const work = readFileSync('src/pages/work/WorkPage.vue', 'utf8')
    const detail = readFileSync('src/features/work-detail/ui/WorkDetailPage.vue', 'utf8')
    expect(work).toContain('route.path === "/tasks" || route.query.tab === "tasks"')
    expect(work).toContain('<div v-if="!isSpecialist" class="work-tab-controls">')
    expect(work).toContain(":title=\"tab === 'tasks' ? t('work.tasks') : t('work.cleanings')\"")
    expect(detail).toContain("props.kind === 'task' && isSpecialist.value")
    expect(detail).toContain("? '/tasks'")
  })

  it('removes cleaner routing chrome from specialist cleaning lists', () => {
    const work = readFileSync('src/pages/work/WorkPage.vue', 'utf8')
    expect(work).toContain('function routesForDayView(cleanings: Cleaning[])')
    expect(work).toContain('return [{ cleanerId: "specialist", cleanerName: "", cleanings }]')
    expect(work).toContain('v-for="route in routesForDayView(day.cleanings)"')
    expect(work).toMatch(/v-if="!isSpecialist"\s+class="work-group-header flex items-center gap-2/)
    expect(work).toMatch(/v-if="!isSpecialist"\s+class="work-route-cleaning-row__position/)
    expect(work).toMatch(/v-if="!isSpecialist"\s+class="work-apartment-header__icon/)
    expect(work).not.toContain('</span>\n                ><span v-if="day.cleanings.some')
  })
})
