const additionalSpecialServiceIconOptions = [
  ['i-lucide-activity', 'Активность'],
  ['i-lucide-air-vent', 'Вентиляция'],
  ['i-lucide-alarm-clock-check', 'Будильник включён'],
  ['i-lucide-alarm-clock-plus', 'Добавить будильник'],
  ['i-lucide-alarm-smoke', 'Датчик дыма'],
  ['i-lucide-ambulance', 'Скорая помощь'],
  ['i-lucide-anchor', 'Якорь'],
  ['i-lucide-armchair', 'Кресло'],
  ['i-lucide-award', 'Награда'],
  ['i-lucide-backpack', 'Рюкзак'],
  ['i-lucide-badge-check', 'Проверено'],
  ['i-lucide-badge-euro', 'Цена в евро'],
  ['i-lucide-badge-percent', 'Акция'],
  ['i-lucide-banana', 'Банан'],
  ['i-lucide-banknote', 'Наличные'],
  ['i-lucide-bed-single', 'Односпальная кровать'],
  ['i-lucide-beef', 'Мясо'],
  ['i-lucide-bell-ring', 'Звонок'],
  ['i-lucide-binoculars', 'Бинокль'],
  ['i-lucide-bird', 'Птица'],
  ['i-lucide-bone', 'Кость'],
  ['i-lucide-book-check', 'Подтверждённая запись'],
  ['i-lucide-book-heart', 'Любимая книга'],
  ['i-lucide-book-open', 'Книга'],
  ['i-lucide-bot', 'Автоматизация'],
  ['i-lucide-briefcase-medical', 'Аптечка'],
  ['i-lucide-brush', 'Щётка'],
  ['i-lucide-building', 'Здание'],
  ['i-lucide-car-front', 'Автомобиль спереди'],
  ['i-lucide-caravan', 'Кемпер'],
  ['i-lucide-castle', 'Замок'],
  ['i-lucide-cctv', 'Видеонаблюдение'],
  ['i-lucide-chart-no-axes-column', 'Статистика'],
  ['i-lucide-chart-pie', 'Диаграмма'],
  ['i-lucide-cherry', 'Вишня'],
  ['i-lucide-church', 'Церковь'],
  ['i-lucide-circle-dollar-sign', 'Цена в долларах'],
  ['i-lucide-circle-parking', 'Парковка'],
  ['i-lucide-citrus', 'Цитрус'],
  ['i-lucide-clipboard-check', 'Чек-лист'],
  ['i-lucide-clipboard-list', 'Список'],
  ['i-lucide-cloud-rain', 'Дождь'],
  ['i-lucide-cloud-sun', 'Переменная облачность'],
  ['i-lucide-compass', 'Компас'],
  ['i-lucide-contact', 'Контакт'],
  ['i-lucide-cookie', 'Печенье'],
  ['i-lucide-croissant', 'Круассан'],
  ['i-lucide-cross', 'Крест'],
  ['i-lucide-door-closed', 'Закрытая дверь'],
  ['i-lucide-door-closed-locked', 'Запертая дверь'],
  ['i-lucide-drill', 'Дрель'],
  ['i-lucide-drumstick', 'Горячее блюдо'],
  ['i-lucide-dumbbell', 'Фитнес'],
  ['i-lucide-ear', 'Слух'],
  ['i-lucide-earth', 'Мир'],
  ['i-lucide-egg', 'Яйцо'],
  ['i-lucide-fan', 'Вентилятор'],
  ['i-lucide-feather', 'Перо'],
  ['i-lucide-fence', 'Ограждение'],
  ['i-lucide-ferris-wheel', 'Колесо обозрения'],
  ['i-lucide-fire-extinguisher', 'Огнетушитель'],
  ['i-lucide-fish', 'Рыба'],
  ['i-lucide-flag', 'Флаг'],
  ['i-lucide-flashlight', 'Фонарик'],
  ['i-lucide-flower-2', 'Цветы'],
  ['i-lucide-fuel', 'Топливо'],
  ['i-lucide-gamepad-2', 'Игры'],
  ['i-lucide-gauge', 'Скорость'],
  ['i-lucide-gavel', 'Правила'],
  ['i-lucide-glasses', 'Очки'],
  ['i-lucide-globe', 'Глобус'],
  ['i-lucide-grape', 'Виноград'],
  ['i-lucide-graduation-cap', 'Обучение'],
  ['i-lucide-guitar', 'Гитара'],
  ['i-lucide-hand-coins', 'Оплата'],
  ['i-lucide-hand-heart', 'Забота'],
  ['i-lucide-hand-platter', 'Обслуживание'],
  ['i-lucide-hard-hat', 'Технические работы'],
  ['i-lucide-headset', 'Поддержка'],
  ['i-lucide-heater', 'Обогреватель'],
  ['i-lucide-hospital', 'Больница'],
  ['i-lucide-ice-cream-cone', 'Мороженое'],
  ['i-lucide-id-card', 'Документ'],
  ['i-lucide-key-square', 'Ключ-карта'],
  ['i-lucide-lamp', 'Лампа'],
  ['i-lucide-lamp-ceiling', 'Потолочный свет'],
  ['i-lucide-lamp-desk', 'Настольная лампа'],
  ['i-lucide-lamp-floor', 'Торшер'],
  ['i-lucide-life-buoy', 'Спасательный круг'],
  ['i-lucide-link', 'Ссылка'],
  ['i-lucide-map-pinned', 'Точка на карте'],
  ['i-lucide-martini', 'Коктейль'],
  ['i-lucide-megaphone', 'Объявление'],
  ['i-lucide-microwave', 'Микроволновка'],
  ['i-lucide-monitor', 'Монитор'],
  ['i-lucide-motorbike', 'Мотоцикл'],
  ['i-lucide-package-check', 'Доставка выполнена'],
  ['i-lucide-package-open', 'Открытая посылка'],
  ['i-lucide-paint-roller', 'Покраска'],
  ['i-lucide-palette', 'Оформление'],
  ['i-lucide-parking-meter', 'Платная парковка'],
  ['i-lucide-pc-case', 'Компьютер'],
  ['i-lucide-person-standing', 'Человек'],
  ['i-lucide-phone-call', 'Телефонный звонок'],
  ['i-lucide-piano', 'Пианино'],
  ['i-lucide-pickaxe', 'Инструмент'],
  ['i-lucide-pill', 'Лекарство'],
  ['i-lucide-plane-landing', 'Прибытие'],
  ['i-lucide-plane-takeoff', 'Отправление'],
  ['i-lucide-plug-zap', 'Зарядка'],
  ['i-lucide-popcorn', 'Попкорн'],
  ['i-lucide-printer', 'Печать'],
  ['i-lucide-projector', 'Проектор'],
  ['i-lucide-rabbit', 'Кролик'],
  ['i-lucide-radio', 'Радио'],
  ['i-lucide-receipt', 'Чек'],
  ['i-lucide-receipt-euro', 'Счёт в евро'],
  ['i-lucide-refrigerator', 'Холодильник'],
  ['i-lucide-route', 'Маршрут'],
  ['i-lucide-sailboat', 'Парусная лодка'],
  ['i-lucide-salad', 'Салат'],
  ['i-lucide-scissors', 'Ножницы'],
  ['i-lucide-search', 'Поиск'],
  ['i-lucide-send', 'Отправить'],
  ['i-lucide-shield-plus', 'Дополнительная защита'],
  ['i-lucide-ship-wheel', 'Штурвал'],
  ['i-lucide-shopping-basket', 'Корзина'],
  ['i-lucide-shopping-cart', 'Тележка'],
  ['i-lucide-signpost', 'Указатель'],
  ['i-lucide-sofa', 'Диван'],
  ['i-lucide-soup', 'Суп'],
  ['i-lucide-speaker', 'Колонка'],
  ['i-lucide-sprout', 'Росток'],
  ['i-lucide-square-parking', 'Парковочное место'],
  ['i-lucide-stethoscope', 'Медицина'],
  ['i-lucide-tag', 'Метка'],
  ['i-lucide-tent', 'Палатка'],
  ['i-lucide-tickets', 'Билеты'],
  ['i-lucide-toilet', 'Туалет'],
  ['i-lucide-traffic-cone', 'Дорожные работы'],
  ['i-lucide-tram-front', 'Трамвай'],
  ['i-lucide-tree-palm', 'Пальма'],
  ['i-lucide-trophy', 'Трофей'],
  ['i-lucide-truck', 'Грузовик'],
  ['i-lucide-utensils-crossed', 'Ресторан'],
  ['i-lucide-vault', 'Сейф'],
  ['i-lucide-vegan', 'Веганское меню'],
  ['i-lucide-volleyball', 'Волейбол'],
  ['i-lucide-wallet', 'Кошелёк'],
  ['i-lucide-watch', 'Наручные часы'],
  ['i-lucide-waypoints', 'Точки маршрута'],
  ['i-lucide-wheat', 'Выпечка'],
  ['i-lucide-wine-off', 'Без алкоголя'],
  ['i-lucide-zap', 'Энергия'],
  ['i-lucide-alarm-clock-off', 'Будильник выключен'],
  ['i-lucide-badge-alert', 'Внимание'],
  ['i-lucide-badge-info', 'Справка'],
  ['i-lucide-badge-minus', 'Убрать отметку'],
  ['i-lucide-badge-plus', 'Добавить отметку'],
  ['i-lucide-badge-x', 'Отклонено'],
  ['i-lucide-battery-charging', 'Батарея заряжается'],
  ['i-lucide-battery-full', 'Полный заряд'],
  ['i-lucide-bluetooth', 'Bluetooth'],
  ['i-lucide-book-copy', 'Копия документа'],
  ['i-lucide-book-key', 'Книга доступа'],
  ['i-lucide-book-user', 'Книга гостей'],
  ['i-lucide-cable', 'Кабель'],
  ['i-lucide-cable-car', 'Канатная дорога'],
  ['i-lucide-calendar-clock', 'Дата и время'],
  ['i-lucide-calendar-heart', 'Особая дата'],
  ['i-lucide-calendar-plus', 'Добавить дату'],
  ['i-lucide-calendar-range', 'Период'],
  ['i-lucide-chart-bar-big', 'График'],
  ['i-lucide-chart-line', 'Динамика'],
  ['i-lucide-chart-spline', 'Тренд'],
  ['i-lucide-circle-gauge', 'Индикатор'],
  ['i-lucide-circle-power', 'Питание'],
  ['i-lucide-clipboard-pen', 'Запись'],
  ['i-lucide-cloud', 'Облако'],
  ['i-lucide-download', 'Скачать'],
  ['i-lucide-eye', 'Просмотр'],
  ['i-lucide-hand-helping', 'Помощь'],
  ['i-lucide-handshake', 'Договорённость'],
  ['i-lucide-headphones', 'Наушники'],
  ['i-lucide-heart-handshake', 'Гостеприимство'],
  ['i-lucide-house-plug', 'Электричество в доме'],
  ['i-lucide-laptop', 'Ноутбук'],
  ['i-lucide-map-plus', 'Добавить место'],
  ['i-lucide-monitor-smartphone', 'Устройства'],
  ['i-lucide-mouse-pointer-click', 'Онлайн-заказ'],
  ['i-lucide-package-plus', 'Добавить посылку'],
  ['i-lucide-paintbrush', 'Кисть'],
  ['i-lucide-plug-2', 'Розетка'],
  ['i-lucide-pocket-knife', 'Складной нож'],
  ['i-lucide-presentation', 'Презентация'],
  ['i-lucide-screen-share', 'Демонстрация экрана'],
  ['i-lucide-smartphone', 'Смартфон'],
  ['i-lucide-tablet', 'Планшет'],
  ['i-lucide-tree-deciduous', 'Дерево'],
  ['i-lucide-upload', 'Загрузить'],
  ['i-lucide-usb', 'USB'],
  ['i-lucide-wind', 'Ветер'],
  ['i-lucide-roller-coaster', 'Аттракцион'],
  ['i-lucide-satellite', 'Спутниковая связь'],
  ['i-lucide-school', 'Школа'],
  ['i-lucide-landmark', 'Достопримечательность'],
  ['i-lucide-languages', 'Перевод'],
  ['i-lucide-locate-fixed', 'Геолокация'],
  ['i-lucide-navigation-2', 'Направление'],
  ['i-lucide-newspaper', 'Газета'],
  ['i-lucide-qr-code', 'QR-код'],
  ['i-lucide-scan-barcode', 'Сканер штрихкода'],
  ['i-lucide-panels-top-left', 'Панели'],
  ['i-lucide-panel-top-open', 'Верхняя панель'],
  ['i-lucide-panel-left-open', 'Боковая панель'],
  ['i-lucide-folder-open', 'Открытая папка'],
  ['i-lucide-file-text', 'Текстовый документ'],
  ['i-lucide-files', 'Документы'],
  ['i-lucide-badge-dollar-sign', 'Цена в долларах'],
  ['i-lucide-circle-percent', 'Процент'],
  ['i-lucide-circle-euro', 'Евро'],
  ['i-lucide-coins', 'Монеты'],
  ['i-lucide-hand-metal', 'Жест'],
  ['i-lucide-heart-pulse', 'Здоровье'],
  ['i-lucide-thermometer', 'Температура'],
  ['i-lucide-syringe', 'Медицинская помощь'],
  ['i-lucide-bandage', 'Первая помощь'],
  ['i-lucide-shield-half', 'Защита'],
  ['i-lucide-shield-alert', 'Предупреждение безопасности'],
  ['i-lucide-key', 'Ключ'],
  ['i-lucide-sparkle', 'Особое предложение'],
  ['i-lucide-candy', 'Конфета'],
  ['i-lucide-candy-cane', 'Праздничная сладость']
] as const

export const specialServiceIconOptions = [
  { name: 'i-lucide-concierge-bell', label: 'Услуга', keywords: 'сервис помощь гостиница' },
  { name: 'i-lucide-car', label: 'Автомобиль', keywords: 'машина трансфер такси' },
  { name: 'i-lucide-car-taxi-front', label: 'Такси', keywords: 'трансфер машина' },
  { name: 'i-lucide-bus-front', label: 'Автобус', keywords: 'трансфер перевозка' },
  { name: 'i-lucide-train-front', label: 'Поезд', keywords: 'трансфер вокзал' },
  { name: 'i-lucide-plane', label: 'Самолёт', keywords: 'аэропорт перелёт трансфер' },
  { name: 'i-lucide-luggage', label: 'Багаж', keywords: 'чемодан хранение' },
  { name: 'i-lucide-map-pin', label: 'Место', keywords: 'локация адрес' },
  { name: 'i-lucide-navigation', label: 'Навигация', keywords: 'маршрут дорога' },
  { name: 'i-lucide-bike', label: 'Велосипед', keywords: 'спорт прокат' },
  { name: 'i-lucide-ship', label: 'Лодка', keywords: 'море прогулка' },
  { name: 'i-lucide-ticket', label: 'Билет', keywords: 'вход экскурсия' },
  { name: 'i-lucide-key-round', label: 'Ключ', keywords: 'доступ замок' },
  { name: 'i-lucide-door-open', label: 'Дверь', keywords: 'вход доступ' },
  { name: 'i-lucide-bed-double', label: 'Кровать', keywords: 'сон спальня' },
  { name: 'i-lucide-bath', label: 'Ванна', keywords: 'ванная спа' },
  { name: 'i-lucide-shower-head', label: 'Душ', keywords: 'ванная вода' },
  { name: 'i-lucide-cooking-pot', label: 'Кастрюля', keywords: 'еда кухня готовка' },
  { name: 'i-lucide-chef-hat', label: 'Шеф-повар', keywords: 'еда кухня ресторан' },
  { name: 'i-lucide-utensils', label: 'Столовые приборы', keywords: 'еда кухня ресторан' },
  { name: 'i-lucide-coffee', label: 'Кофе', keywords: 'напиток завтрак' },
  { name: 'i-lucide-cup-soda', label: 'Напиток', keywords: 'вода напиток' },
  { name: 'i-lucide-wine', label: 'Вино', keywords: 'напиток бар' },
  { name: 'i-lucide-beer', label: 'Пиво', keywords: 'напиток бар' },
  { name: 'i-lucide-cake-slice', label: 'Торт', keywords: 'еда праздник' },
  { name: 'i-lucide-ice-cream-bowl', label: 'Мороженое', keywords: 'еда десерт' },
  { name: 'i-lucide-sandwich', label: 'Сэндвич', keywords: 'еда завтрак' },
  { name: 'i-lucide-pizza', label: 'Пицца', keywords: 'еда доставка' },
  { name: 'i-lucide-apple', label: 'Фрукты', keywords: 'еда завтрак' },
  { name: 'i-lucide-milk', label: 'Молоко', keywords: 'еда завтрак' },
  { name: 'i-lucide-baby', label: 'Ребёнок', keywords: 'дети кроватка' },
  { name: 'i-lucide-accessibility', label: 'Доступность', keywords: 'инвалид коляска' },
  { name: 'i-lucide-dog', label: 'Собака', keywords: 'питомец животное' },
  { name: 'i-lucide-cat', label: 'Кошка', keywords: 'питомец животное' },
  { name: 'i-lucide-heart', label: 'Забота', keywords: 'любовь сервис' },
  { name: 'i-lucide-star', label: 'Премиум', keywords: 'избранное рейтинг' },
  { name: 'i-lucide-sparkles', label: 'Праздник', keywords: 'подарок премиум' },
  { name: 'i-lucide-sun', label: 'Солнце', keywords: 'лето отдых' },
  { name: 'i-lucide-moon', label: 'Ночь', keywords: 'сон вечер' },
  { name: 'i-lucide-snowflake', label: 'Снег', keywords: 'зима холод' },
  { name: 'i-lucide-umbrella', label: 'Зонт', keywords: 'дождь погода' },
  { name: 'i-lucide-mountain', label: 'Горы', keywords: 'банско лыжи отдых' },
  { name: 'i-lucide-waves', label: 'Вода', keywords: 'бассейн море отдых' },
  { name: 'i-lucide-tree-pine', label: 'Природа', keywords: 'лес горы отдых' },
  { name: 'i-lucide-flame', label: 'Камин', keywords: 'огонь тепло' },
  { name: 'i-lucide-music', label: 'Музыка', keywords: 'развлечения' },
  { name: 'i-lucide-party-popper', label: 'Праздник', keywords: 'вечеринка событие' },
  { name: 'i-lucide-camera', label: 'Фото', keywords: 'съёмка память' },
  { name: 'i-lucide-image', label: 'Изображение', keywords: 'фото' },
  { name: 'i-lucide-clapperboard', label: 'Кино', keywords: 'развлечения' },
  { name: 'i-lucide-tv', label: 'Телевизор', keywords: 'развлечения' },
  { name: 'i-lucide-wifi', label: 'Wi-Fi', keywords: 'интернет связь' },
  { name: 'i-lucide-phone', label: 'Телефон', keywords: 'связь звонок' },
  { name: 'i-lucide-mail', label: 'Почта', keywords: 'сообщение связь' },
  { name: 'i-lucide-message-circle', label: 'Сообщение', keywords: 'связь чат' },
  { name: 'i-lucide-info', label: 'Информация', keywords: 'помощь' },
  { name: 'i-lucide-circle-question-mark', label: 'Помощь', keywords: 'поддержка' },
  { name: 'i-lucide-bell', label: 'Уведомление', keywords: 'сигнал' },
  { name: 'i-lucide-calendar-days', label: 'Календарь', keywords: 'дата бронирование' },
  { name: 'i-lucide-clock-3', label: 'Время', keywords: 'часы' },
  { name: 'i-lucide-alarm-clock', label: 'Будильник', keywords: 'время' },
  { name: 'i-lucide-calendar-check-2', label: 'Подтверждение', keywords: 'бронь готово' },
  { name: 'i-lucide-house', label: 'Дом', keywords: 'жильё' },
  { name: 'i-lucide-building-2', label: 'Здание', keywords: 'апартамент отель' },
  { name: 'i-lucide-hotel', label: 'Отель', keywords: 'жильё апартаменты' },
  { name: 'i-lucide-warehouse', label: 'Склад', keywords: 'хранение' },
  { name: 'i-lucide-store', label: 'Магазин', keywords: 'покупки' },
  { name: 'i-lucide-briefcase-business', label: 'Бизнес', keywords: 'работа' },
  { name: 'i-lucide-shopping-bag', label: 'Покупки', keywords: 'магазин' },
  { name: 'i-lucide-package', label: 'Посылка', keywords: 'доставка' },
  { name: 'i-lucide-boxes', label: 'Коробки', keywords: 'хранение доставка' },
  { name: 'i-lucide-spray-can', label: 'Спрей', keywords: 'уборка чистота' },
  { name: 'i-lucide-brush-cleaning', label: 'Щётка', keywords: 'уборка чистота' },
  { name: 'i-lucide-broom', label: 'Метла', keywords: 'уборка чистота' },
  { name: 'i-lucide-soap-dispenser-droplet', label: 'Мыло', keywords: 'ванная чистота' },
  { name: 'i-lucide-washing-machine', label: 'Стирка', keywords: 'бельё прачечная' },
  { name: 'i-lucide-shirt', label: 'Глажка', keywords: 'бельё стирка одежда' },
  { name: 'i-lucide-wrench', label: 'Ремонт', keywords: 'мастер обслуживание' },
  { name: 'i-lucide-hammer', label: 'Мастер', keywords: 'ремонт обслуживание' },
  { name: 'i-lucide-tool-case', label: 'Инструмент', keywords: 'ремонт обслуживание' },
  { name: 'i-lucide-plug', label: 'Электричество', keywords: 'техника' },
  { name: 'i-lucide-lightbulb', label: 'Свет', keywords: 'лампа электричество' },
  { name: 'i-lucide-lock-keyhole', label: 'Безопасность', keywords: 'замок доступ' },
  { name: 'i-lucide-shield-check', label: 'Защита', keywords: 'безопасность' },
  { name: 'i-lucide-circle-check', label: 'Готово', keywords: 'подтверждение' },
  { name: 'i-lucide-circle-alert', label: 'Важно', keywords: 'предупреждение' },
  { name: 'i-lucide-percent', label: 'Скидка', keywords: 'цена акция' },
  { name: 'i-lucide-euro', label: 'Евро', keywords: 'цена деньги' },
  { name: 'i-lucide-wallet-cards', label: 'Оплата', keywords: 'деньги карта' },
  { name: 'i-lucide-credit-card', label: 'Карта', keywords: 'оплата деньги' },
  { name: 'i-lucide-gift', label: 'Подарок', keywords: 'сюрприз праздник' },
  { name: 'i-lucide-medal', label: 'Награда', keywords: 'премиум' },
  { name: 'i-lucide-crown', label: 'Люкс', keywords: 'премиум' },
  { name: 'i-lucide-gem', label: 'Премиум', keywords: 'люкс' },
  { name: 'i-lucide-leaf', label: 'Эко', keywords: 'природа экологично' },
  { name: 'i-lucide-recycle', label: 'Переработка', keywords: 'эко природа' },
  { name: 'i-lucide-paw-print', label: 'Питомец', keywords: 'животное' },
  ...additionalSpecialServiceIconOptions.map(([name, label]) => ({ name, label, keywords: '' }))
] as const

export type SpecialServiceIconName = typeof specialServiceIconOptions[number]['name']
export const specialServiceIconNames = specialServiceIconOptions.map(option => option.name) as [SpecialServiceIconName, ...SpecialServiceIconName[]]
export const specialServiceIconClientNames = specialServiceIconOptions.map(option => `lucide:${option.name.slice('i-lucide-'.length)}`)
