export const specialServiceIconOptions = [
  { name: 'i-lucide-concierge-bell', label: 'Услуга', keywords: 'сервис помощь гостиница' },
  { name: 'i-lucide-car', label: 'Автомобиль', keywords: 'машина трансфер такси' },
  { name: 'i-lucide-car-taxi-front', label: 'Такси', keywords: 'трансфер машина' },
  { name: 'i-lucide-bus-front', label: 'Автобус', keywords: 'трансфер перевозка' },
  { name: 'i-lucide-train-front', label: 'Поезд', keywords: 'трансфер вокзал' },
  { name: 'i-lucide-plane', label: 'Самолёт', keywords: 'аэропорт перелёт трансфер' },
  { name: 'i-lucide-luggage', label: 'Багаж', keywords: 'чемодан хранение' },
  { name: 'i-lucide-map-pin', label: 'Место', keywords: 'локация адрес' },
  { name: 'i-lucide-navigation', label: 'Навигация', keywords: 'маршрут дорога' },
  { name: 'i-lucide-bike', label: 'Велосипед', keywords: 'спорт прокат' },
  { name: 'i-lucide-ship', label: 'Лодка', keywords: 'море прогулка' },
  { name: 'i-lucide-ticket', label: 'Билет', keywords: 'вход экскурсия' },
  { name: 'i-lucide-key-round', label: 'Ключ', keywords: 'доступ замок' },
  { name: 'i-lucide-door-open', label: 'Дверь', keywords: 'вход доступ' },
  { name: 'i-lucide-bed-double', label: 'Кровать', keywords: 'сон спальня' },
  { name: 'i-lucide-bath', label: 'Ванна', keywords: 'ванная спа' },
  { name: 'i-lucide-shower-head', label: 'Душ', keywords: 'ванная вода' },
  { name: 'i-lucide-cooking-pot', label: 'Кастрюля', keywords: 'еда кухня готовка' },
  { name: 'i-lucide-chef-hat', label: 'Шеф-повар', keywords: 'еда кухня ресторан' },
  { name: 'i-lucide-utensils', label: 'Столовые приборы', keywords: 'еда кухня ресторан' },
  { name: 'i-lucide-coffee', label: 'Кофе', keywords: 'напиток завтрак' },
  { name: 'i-lucide-cup-soda', label: 'Напиток', keywords: 'вода напиток' },
  { name: 'i-lucide-wine', label: 'Вино', keywords: 'напиток бар' },
  { name: 'i-lucide-beer', label: 'Пиво', keywords: 'напиток бар' },
  { name: 'i-lucide-cake-slice', label: 'Торт', keywords: 'еда праздник' },
  { name: 'i-lucide-ice-cream-bowl', label: 'Мороженое', keywords: 'еда десерт' },
  { name: 'i-lucide-sandwich', label: 'Сэндвич', keywords: 'еда завтрак' },
  { name: 'i-lucide-pizza', label: 'Пицца', keywords: 'еда доставка' },
  { name: 'i-lucide-apple', label: 'Фрукты', keywords: 'еда завтрак' },
  { name: 'i-lucide-milk', label: 'Молоко', keywords: 'еда завтрак' },
  { name: 'i-lucide-baby', label: 'Ребёнок', keywords: 'дети кроватка' },
  { name: 'i-lucide-accessibility', label: 'Доступность', keywords: 'инвалид коляска' },
  { name: 'i-lucide-dog', label: 'Собака', keywords: 'питомец животное' },
  { name: 'i-lucide-cat', label: 'Кошка', keywords: 'питомец животное' },
  { name: 'i-lucide-heart', label: 'Забота', keywords: 'любовь сервис' },
  { name: 'i-lucide-star', label: 'Премиум', keywords: 'избранное рейтинг' },
  { name: 'i-lucide-sparkles', label: 'Праздник', keywords: 'подарок премиум' },
  { name: 'i-lucide-sun', label: 'Солнце', keywords: 'лето отдых' },
  { name: 'i-lucide-moon', label: 'Ночь', keywords: 'сон вечер' },
  { name: 'i-lucide-snowflake', label: 'Снег', keywords: 'зима холод' },
  { name: 'i-lucide-umbrella', label: 'Зонт', keywords: 'дождь погода' },
  { name: 'i-lucide-mountain', label: 'Горы', keywords: 'банско лыжи отдых' },
  { name: 'i-lucide-waves', label: 'Вода', keywords: 'бассейн море отдых' },
  { name: 'i-lucide-tree-pine', label: 'Природа', keywords: 'лес горы отдых' },
  { name: 'i-lucide-flame', label: 'Камин', keywords: 'огонь тепло' },
  { name: 'i-lucide-music', label: 'Музыка', keywords: 'развлечения' },
  { name: 'i-lucide-party-popper', label: 'Праздник', keywords: 'вечеринка событие' },
  { name: 'i-lucide-camera', label: 'Фото', keywords: 'съёмка память' },
  { name: 'i-lucide-image', label: 'Изображение', keywords: 'фото' },
  { name: 'i-lucide-clapperboard', label: 'Кино', keywords: 'развлечения' },
  { name: 'i-lucide-tv', label: 'Телевизор', keywords: 'развлечения' },
  { name: 'i-lucide-wifi', label: 'Wi-Fi', keywords: 'интернет связь' },
  { name: 'i-lucide-phone', label: 'Телефон', keywords: 'связь звонок' },
  { name: 'i-lucide-mail', label: 'Почта', keywords: 'сообщение связь' },
  { name: 'i-lucide-message-circle', label: 'Сообщение', keywords: 'связь чат' },
  { name: 'i-lucide-info', label: 'Информация', keywords: 'помощь' },
  { name: 'i-lucide-circle-question-mark', label: 'Помощь', keywords: 'поддержка' },
  { name: 'i-lucide-bell', label: 'Уведомление', keywords: 'сигнал' },
  { name: 'i-lucide-calendar-days', label: 'Календарь', keywords: 'дата бронирование' },
  { name: 'i-lucide-clock-3', label: 'Время', keywords: 'часы' },
  { name: 'i-lucide-alarm-clock', label: 'Будильник', keywords: 'время' },
  { name: 'i-lucide-calendar-check-2', label: 'Подтверждение', keywords: 'бронь готово' },
  { name: 'i-lucide-house', label: 'Дом', keywords: 'жильё' },
  { name: 'i-lucide-building-2', label: 'Здание', keywords: 'апартамент отель' },
  { name: 'i-lucide-hotel', label: 'Отель', keywords: 'жильё апартаменты' },
  { name: 'i-lucide-warehouse', label: 'Склад', keywords: 'хранение' },
  { name: 'i-lucide-store', label: 'Магазин', keywords: 'покупки' },
  { name: 'i-lucide-briefcase-business', label: 'Бизнес', keywords: 'работа' },
  { name: 'i-lucide-shopping-bag', label: 'Покупки', keywords: 'магазин' },
  { name: 'i-lucide-package', label: 'Посылка', keywords: 'доставка' },
  { name: 'i-lucide-boxes', label: 'Коробки', keywords: 'хранение доставка' },
  { name: 'i-lucide-spray-can', label: 'Спрей', keywords: 'уборка чистота' },
  { name: 'i-lucide-brush-cleaning', label: 'Щётка', keywords: 'уборка чистота' },
  { name: 'i-lucide-broom', label: 'Метла', keywords: 'уборка чистота' },
  { name: 'i-lucide-soap-dispenser-droplet', label: 'Мыло', keywords: 'ванная чистота' },
  { name: 'i-lucide-washing-machine', label: 'Стирка', keywords: 'бельё прачечная' },
  { name: 'i-lucide-shirt', label: 'Одежда', keywords: 'бельё стирка' },
  { name: 'i-lucide-shirt', label: 'Глажка', keywords: 'бельё стирка одежда' },
  { name: 'i-lucide-wrench', label: 'Ремонт', keywords: 'мастер обслуживание' },
  { name: 'i-lucide-hammer', label: 'Мастер', keywords: 'ремонт обслуживание' },
  { name: 'i-lucide-tool-case', label: 'Инструмент', keywords: 'ремонт обслуживание' },
  { name: 'i-lucide-plug', label: 'Электричество', keywords: 'техника' },
  { name: 'i-lucide-lightbulb', label: 'Свет', keywords: 'лампа электричество' },
  { name: 'i-lucide-lock-keyhole', label: 'Безопасность', keywords: 'замок доступ' },
  { name: 'i-lucide-shield-check', label: 'Защита', keywords: 'безопасность' },
  { name: 'i-lucide-circle-check', label: 'Готово', keywords: 'подтверждение' },
  { name: 'i-lucide-circle-alert', label: 'Важно', keywords: 'предупреждение' },
  { name: 'i-lucide-percent', label: 'Скидка', keywords: 'цена акция' },
  { name: 'i-lucide-euro', label: 'Евро', keywords: 'цена деньги' },
  { name: 'i-lucide-wallet-cards', label: 'Оплата', keywords: 'деньги карта' },
  { name: 'i-lucide-credit-card', label: 'Карта', keywords: 'оплата деньги' },
  { name: 'i-lucide-gift', label: 'Подарок', keywords: 'сюрприз праздник' },
  { name: 'i-lucide-medal', label: 'Награда', keywords: 'премиум' },
  { name: 'i-lucide-crown', label: 'Люкс', keywords: 'премиум' },
  { name: 'i-lucide-gem', label: 'Премиум', keywords: 'люкс' },
  { name: 'i-lucide-leaf', label: 'Эко', keywords: 'природа экологично' },
  { name: 'i-lucide-recycle', label: 'Переработка', keywords: 'эко природа' },
  { name: 'i-lucide-paw-print', label: 'Питомец', keywords: 'животное' }
] as const

export type SpecialServiceIconName = typeof specialServiceIconOptions[number]['name']
export const specialServiceIconNames = specialServiceIconOptions.map(option => option.name) as [SpecialServiceIconName, ...SpecialServiceIconName[]]
export const specialServiceIconClientNames = specialServiceIconOptions.map(option => `lucide:${option.name.slice('i-lucide-'.length)}`)
