<script setup lang="ts">
import Decimal from 'decimal.js'
import type { Cleaning } from '#fsd/entities/cleaning'
import type { Task } from '#fsd/entities/task'
import type { Apartment } from '#fsd/entities/apartment'
import { formatDate, formatEuro } from '#fsd/shared/lib'
import { useCurrentUser } from '#fsd/shared/auth'
import { DateInput, EmptyState, MoneyInput, PageHeader, StatusBadge } from '#fsd/shared/ui'

const currentUser = useCurrentUser()
const tab = ref<'cleanings' | 'tasks'>('cleanings')
const [{ data: cleanings, refresh: refreshCleanings }, { data: tasks, refresh: refreshTasks }, { data: apartments }] = await Promise.all([
  useAsyncData('work-cleanings', () => $fetch<Cleaning[]>('/api/cleanings')),
  useAsyncData('work-tasks', () => $fetch<Task[]>('/api/tasks')),
  useAsyncData('work-apartments', () => $fetch<Apartment[]>('/api/apartments'))
])
const { data: team } = await useAsyncData('work-team', () => currentUser.value?.roles.some(role => ['administrator', 'manager'].includes(role)) ? $fetch<Array<{ id: string; name: string; roles: string[] }>>('/api/users/assignable') : Promise.resolve([]))

const selected = ref<{ kind: 'cleaning' | 'task'; id: string; checklist: Array<{ label: string; checked: boolean }> } | null>(null)
const completeOpen = computed({ get: () => Boolean(selected.value), set: value => { if (!value) selected.value = null } })
const comment = ref(''); const hasProblem = ref(false); const problemDescription = ref(''); const photo = ref<File | null>(null); const pending = ref(false); const error = ref('')
const taskOpen = ref(false)
const taskForm = reactive({ apartmentId: '', assigneeId: 'unassigned', title: '', description: '', priority: 'normal', dueOn: '', ownerCostEur: 0 as number | null, checklist: [] as Array<{ label: string; checked: boolean }> })
const assignOpen = ref(false); const cleaningToAssign = ref<Cleaning | null>(null); const cleanerIds = ref<string[]>([]); const scheduledOn = ref('')
const tariffOpen = ref(false); const tariffCleaning = ref<Cleaning | null>(null)
const tariffForm = reactive({ cleanerPoolEur: 0 as number | null, laundryEur: 0 as number | null, serviceEur: 0 as number | null, reason: '' })
const tariffTotalEur = computed(() => Number(new Decimal(tariffForm.cleanerPoolEur ?? 0).plus(tariffForm.laundryEur ?? 0).plus(tariffForm.serviceEur ?? 0).toDecimalPlaces(2, Decimal.ROUND_HALF_UP)))
const stockOpen = ref(false); const stockWork = ref<{ kind: 'cleaning' | 'task'; id: string; apartmentId: string } | null>(null)
const stockItems = ref<Array<{ consumable: { id: string; name: string; unit: string }; quantity: number }>>([])
const usageForm = reactive({ consumableId: '', quantity: 1, note: '' })

const statusLabels: Record<string, string> = { unassigned: 'Без исполнителя', assigned: 'Назначено', in_progress: 'В работе', completed: 'Завершено', canceled: 'Отменено', open: 'Открыта' }
const statusTones: Record<string, 'neutral' | 'success' | 'warning' | 'danger' | 'info'> = { unassigned: 'warning', assigned: 'info', in_progress: 'warning', completed: 'success', canceled: 'neutral', open: 'info' }
const priorityLabels: Record<string, string> = { low: 'Низкий', normal: 'Обычный', high: 'Высокий', urgent: 'Срочный' }
function cleaningAmount(cleaning: Cleaning) { return cleaning.tariffSnapshot.ownerTotalEur ?? cleaning.tariffSnapshot.cleanerPoolEur ?? 0 }
function cleaningAmountLabel(cleaning: Cleaning) { return cleaning.tariffSnapshot.ownerTotalEur !== undefined ? 'Стоимость' : 'Общий фонд' }
function selectPhoto(event: Event) { photo.value = (event.target as HTMLInputElement).files?.[0] ?? null }
function openComplete(kind: 'cleaning' | 'task', work: Cleaning | Task) { selected.value = { kind, id: work.id, checklist: work.checklist.map(item => ({ ...item })) }; comment.value = ''; hasProblem.value = false; problemDescription.value = ''; photo.value = null; error.value = '' }
async function refreshWork() { await Promise.all([refreshCleanings(), refreshTasks()]) }
async function start(kind: 'cleaning' | 'task', id: string) { await $fetch(`/api/${kind}s/${id}/start`, { method: 'POST' }); await refreshWork() }
async function complete() { if (!selected.value) return; pending.value = true; error.value = ''; try { if (photo.value) { const upload = new FormData(); upload.set('entityType', selected.value.kind); upload.set('entityId', selected.value.id); upload.set('file', photo.value); await $fetch('/api/attachments', { method: 'POST', body: upload }) }; await $fetch(`/api/${selected.value.kind}s/${selected.value.id}/complete`, { method: 'POST', body: { checklist: selected.value.checklist, comment: comment.value, hasProblem: hasProblem.value, problemDescription: problemDescription.value } }); selected.value = null; await refreshWork() } catch (cause: any) { error.value = cause?.data?.statusMessage ?? 'Не удалось завершить работу' } finally { pending.value = false } }
async function cancelTask(id: string) { try { await $fetch(`/api/tasks/${id}`, { method: 'PATCH', body: { status: 'canceled' } }); await refreshTasks() } catch (cause: any) { error.value = cause?.data?.statusMessage ?? 'Не удалось отменить задачу' } }
async function createTask() { pending.value = true; error.value = ''; try { const { assigneeId, ...payload } = taskForm; await $fetch('/api/tasks', { method: 'POST', body: { ...payload, ownerCostEur: payload.ownerCostEur ?? 0, assigneeId: assigneeId === 'unassigned' ? null : assigneeId, dueOn: taskForm.dueOn || null } }); taskOpen.value = false; await refreshTasks() } catch (cause: any) { error.value = cause?.data?.statusMessage ?? 'Не удалось создать задачу' } finally { pending.value = false } }
function openAssign(cleaning: Cleaning) { cleaningToAssign.value = cleaning; cleanerIds.value = cleaning.assignments.map(item => item.cleaner.id); scheduledOn.value = cleaning.scheduledOn ?? ''; assignOpen.value = true; error.value = '' }
async function assignCleaners() { if (!cleaningToAssign.value) return; pending.value = true; try { await $fetch(`/api/cleanings/${cleaningToAssign.value.id}/assignees`, { method: 'PUT', body: { cleanerIds: cleanerIds.value, scheduledOn: scheduledOn.value } }); assignOpen.value = false; await refreshCleanings() } catch (cause: any) { error.value = cause?.data?.statusMessage ?? 'Не удалось назначить уборщиц' } finally { pending.value = false } }
function openTariff(cleaning: Cleaning) { tariffCleaning.value = cleaning; Object.assign(tariffForm, { cleanerPoolEur: cleaning.tariffSnapshot.cleanerPoolEur ?? 0, laundryEur: cleaning.tariffSnapshot.laundryEur ?? 0, serviceEur: cleaning.tariffSnapshot.serviceEur ?? 0, reason: '' }); tariffOpen.value = true; error.value = '' }
async function saveTariff() { if (!tariffCleaning.value) return; pending.value = true; try { await $fetch(`/api/cleanings/${tariffCleaning.value.id}/tariff`, { method: 'PATCH', body: tariffForm }); tariffOpen.value = false; await refreshCleanings() } catch (cause: any) { error.value = cause?.data?.statusMessage ?? 'Не удалось изменить тариф' } finally { pending.value = false } }
async function openStock(kind: 'cleaning' | 'task', work: Cleaning | Task) {
  stockWork.value = { kind, id: work.id, apartmentId: work.apartmentId }
  Object.assign(usageForm, { consumableId: '', quantity: 1, note: '' })
  error.value = ''
  const endpoint = `/api/inventory/${work.apartmentId}` as string
  stockItems.value = await $fetch<Array<{ consumable: { id: string; name: string; unit: string }; quantity: number }>>(endpoint)
  stockOpen.value = true
}
async function recordUsage() { if (!stockWork.value) return; pending.value = true; try { await $fetch('/api/inventory/use', { method: 'POST', body: { apartmentId: stockWork.value.apartmentId, sourceType: stockWork.value.kind, sourceId: stockWork.value.id, ...usageForm } }); stockOpen.value = false } catch (cause: any) { error.value = cause?.data?.statusMessage ?? 'Не удалось списать расходник' } finally { pending.value = false } }
</script>

<template>
  <section class="page-wrap space-y-6">
    <PageHeader title="Работы" description="Уборки и задачи по апартаментам."><template #actions><UButton v-if="currentUser?.roles.some(role => ['administrator', 'manager'].includes(role))" icon="i-lucide-plus" @click="taskOpen = true">Новая задача</UButton></template></PageHeader>
    <UFieldGroup><UButton :variant="tab === 'cleanings' ? 'solid' : 'soft'" @click="tab = 'cleanings'">Уборки <UBadge color="neutral" variant="soft">{{ cleanings?.length ?? 0 }}</UBadge></UButton><UButton :variant="tab === 'tasks' ? 'solid' : 'soft'" @click="tab = 'tasks'">Задачи <UBadge color="neutral" variant="soft">{{ tasks?.length ?? 0 }}</UBadge></UButton></UFieldGroup>

    <div v-if="tab === 'cleanings' && cleanings?.length" class="surface divide-y divide-[var(--color-line)] px-5 sm:px-6">
      <article v-for="cleaning in cleanings" :key="cleaning.id" class="py-5">
        <div class="flex flex-col gap-4 lg:flex-row lg:items-center">
          <div class="flex min-w-0 flex-1 gap-4"><div class="grid size-11 shrink-0 place-items-center rounded-xl bg-[var(--color-primary-soft)] text-[var(--color-primary)]"><UIcon name="i-lucide-sparkles" class="size-5" /></div><div class="min-w-0"><p class="truncate font-semibold">{{ cleaning.apartment.name }} · {{ cleaning.apartment.hotel.name }}</p><p class="mt-1 text-sm text-[var(--color-muted)]">{{ cleaning.scheduledOn ? formatDate(cleaning.scheduledOn) : 'Дата не назначена' }} · {{ cleaningAmountLabel(cleaning) }} {{ formatEuro(cleaningAmount(cleaning)) }}</p><a class="mt-1 inline-flex text-sm font-medium text-[var(--color-primary)]" :href="`https://www.google.com/maps/search/?api=1&query=${cleaning.apartment.hotel.latitude},${cleaning.apartment.hotel.longitude}`" target="_blank">{{ cleaning.apartment.hotel.address }} <UIcon name="i-lucide-external-link" class="ml-1 size-4" /></a><p v-if="cleaning.assignments.length" class="mt-2 text-xs text-[var(--color-muted)]">Исполнители: {{ cleaning.assignments.map(item => item.cleaner.name).join(', ') }}</p></div></div>
          <div class="flex flex-wrap items-center gap-2"><StatusBadge :label="statusLabels[cleaning.status] ?? cleaning.status" :tone="statusTones[cleaning.status] ?? 'neutral'" /><UButton v-if="currentUser?.roles.includes('administrator') && !['completed','canceled'].includes(cleaning.status)" size="sm" variant="soft" @click="openAssign(cleaning)">Назначить</UButton><UButton v-if="currentUser?.roles.includes('administrator') && !['completed','canceled'].includes(cleaning.status)" size="sm" color="neutral" variant="ghost" @click="openTariff(cleaning)">Тариф</UButton><UButton v-if="['assigned','in_progress'].includes(cleaning.status)" size="sm" color="neutral" variant="ghost" @click="openStock('cleaning', cleaning)">Списать</UButton><UButton v-if="cleaning.status === 'assigned'" size="sm" variant="soft" @click="start('cleaning', cleaning.id)">Начать</UButton><UButton v-if="['assigned','in_progress'].includes(cleaning.status)" size="sm" @click="openComplete('cleaning', cleaning)">Завершить</UButton></div>
        </div>
        <UAlert v-if="cleaning.hasProblem" class="mt-4" color="error" variant="soft" icon="i-lucide-circle-alert" title="Проблема" :description="cleaning.problemDescription" />
      </article>
    </div>
    <EmptyState v-else-if="tab === 'cleanings'" icon="i-lucide-sparkles" title="Уборок пока нет" description="Они появляются автоматически при создании заезда." />

    <div v-if="tab === 'tasks' && tasks?.length" class="surface divide-y divide-[var(--color-line)] px-5 sm:px-6">
      <article v-for="task in tasks" :key="task.id" class="py-5">
        <div class="flex flex-col gap-4 lg:flex-row lg:items-center"><div class="flex min-w-0 flex-1 gap-4"><div class="grid size-11 shrink-0 place-items-center rounded-xl bg-[#edf3f7] text-[#356882]"><UIcon name="i-lucide-clipboard-check" class="size-5" /></div><div class="min-w-0"><p class="truncate font-semibold">{{ task.title }}</p><p class="mt-1 text-sm text-[var(--color-muted)]">{{ task.apartment.name }} · {{ priorityLabels[task.priority] ?? task.priority }} приоритет</p><a class="mt-1 inline-flex text-sm font-medium text-[var(--color-primary)]" :href="`https://www.google.com/maps/search/?api=1&query=${task.apartment.hotel.latitude},${task.apartment.hotel.longitude}`" target="_blank">{{ task.apartment.hotel.address }} <UIcon name="i-lucide-external-link" class="ml-1 size-4" /></a></div></div><div class="flex flex-wrap items-center gap-2"><StatusBadge :label="statusLabels[task.status] ?? task.status" :tone="statusTones[task.status] ?? 'neutral'" /><UButton v-if="['open','in_progress'].includes(task.status)" size="sm" color="neutral" variant="ghost" @click="openStock('task', task)">Списать</UButton><UButton v-if="task.status === 'open'" size="sm" variant="soft" @click="start('task', task.id)">Начать</UButton><UButton v-if="['open','in_progress'].includes(task.status)" size="sm" @click="openComplete('task', task)">Завершить</UButton><UButton v-if="currentUser?.roles.some(role => ['administrator', 'manager'].includes(role)) && ['open','in_progress'].includes(task.status)" size="sm" color="error" variant="ghost" @click="cancelTask(task.id)">Отменить</UButton></div></div>
        <UAlert v-if="task.hasProblem" class="mt-4" color="error" variant="soft" icon="i-lucide-circle-alert" title="Проблема" :description="task.problemDescription" />
      </article>
    </div>
    <EmptyState v-else-if="tab === 'tasks'" icon="i-lucide-clipboard-check" title="Задач пока нет" description="Создайте задачу и назначьте исполнителя."><template #actions><UButton v-if="currentUser?.roles.some(role => ['administrator', 'manager'].includes(role))" @click="taskOpen = true">Новая задача</UButton></template></EmptyState>

    <USlideover v-model:open="taskOpen" title="Новая задача"><template #body><form class="form-grid" @submit.prevent="createTask"><UFormField label="Апартамент"><USelect v-model="taskForm.apartmentId" :items="(apartments ?? []).map(apartment => ({ label: `${apartment.name} · ${apartment.hotel.name}`, value: apartment.id }))" class="w-full" required /></UFormField><UFormField label="Что нужно сделать"><UInput v-model="taskForm.title" required /></UFormField><UFormField label="Описание"><UTextarea v-model="taskForm.description" /></UFormField><UFormField label="Приоритет"><USelect v-model="taskForm.priority" :items="Object.entries(priorityLabels).map(([value, label]) => ({ value, label }))" class="w-full" /></UFormField><UFormField label="Исполнитель"><USelect v-model="taskForm.assigneeId" :items="[{ label: 'Без исполнителя', value: 'unassigned' }, ...(team ?? []).map(member => ({ label: member.name, value: member.id }))]" class="w-full" /></UFormField><UFormField v-if="currentUser?.roles.includes('administrator')" label="Стоимость управляющему"><MoneyInput v-model="taskForm.ownerCostEur" /></UFormField><UFormField label="Срок"><DateInput v-model="taskForm.dueOn" /></UFormField><UAlert v-if="error" color="error" variant="soft" :description="error" /><div class="form-actions"><UButton color="neutral" variant="ghost" @click="taskOpen = false">Отмена</UButton><UButton type="submit" :loading="pending">Создать задачу</UButton></div></form></template></USlideover>

    <USlideover v-model:open="tariffOpen" title="Тариф уборки"><template #body><form class="form-grid" @submit.prevent="saveTariff"><div class="rounded-xl bg-[var(--color-primary-soft)] px-4 py-3"><p class="text-sm text-[var(--color-muted)]">Общая стоимость</p><p class="mt-1 text-xl font-semibold tabular-nums text-[var(--color-text)]">{{ formatEuro(tariffTotalEur) }}</p></div><div class="grid gap-4 sm:grid-cols-3"><UFormField label="Уборка"><MoneyInput v-model="tariffForm.cleanerPoolEur" required /></UFormField><UFormField label="Стирка"><MoneyInput v-model="tariffForm.laundryEur" required /></UFormField><UFormField label="Сервис"><MoneyInput v-model="tariffForm.serviceEur" required /></UFormField></div><UFormField label="Причина изменения"><UTextarea v-model="tariffForm.reason" required /></UFormField><UAlert v-if="error" color="error" variant="soft" :description="error" /><div class="form-actions"><UButton color="neutral" variant="ghost" @click="tariffOpen = false">Отмена</UButton><UButton type="submit" :loading="pending">Сохранить тариф</UButton></div></form></template></USlideover>

    <USlideover v-model:open="assignOpen" title="Назначить уборщиц"><template #body><form class="form-grid" @submit.prevent="assignCleaners"><p class="text-sm text-[var(--color-muted)]">Все выбранные уборщицы видят один общий фонд.</p><UFormField label="Дата уборки"><DateInput v-model="scheduledOn" required /></UFormField><label v-for="member in team?.filter(member => member.roles.includes('cleaner'))" :key="member.id" class="flex min-h-11 items-center gap-3 rounded-xl bg-[#f4f8f6] px-3"><input v-model="cleanerIds" type="checkbox" :value="member.id">{{ member.name }}</label><UAlert v-if="error" color="error" variant="soft" :description="error" /><div class="form-actions"><UButton color="neutral" variant="ghost" @click="assignOpen = false">Отмена</UButton><UButton type="submit" :loading="pending" :disabled="!cleanerIds.length || !scheduledOn">Сохранить</UButton></div></form></template></USlideover>

    <USlideover v-model:open="stockOpen" title="Списать расходник"><template #body><form class="form-grid" @submit.prevent="recordUsage"><UFormField label="Расходник"><USelect v-model="usageForm.consumableId" :items="stockItems.filter(item => item.quantity > 0).map(item => ({ label: `${item.consumable.name} · ${item.quantity} ${item.consumable.unit}`, value: item.consumable.id }))" class="w-full" required /></UFormField><UFormField label="Количество"><UInput v-model.number="usageForm.quantity" type="number" min=".001" step=".001" required /></UFormField><UFormField label="Комментарий"><UInput v-model="usageForm.note" /></UFormField><UAlert v-if="error" color="error" variant="soft" :description="error" /><div class="form-actions"><UButton color="neutral" variant="ghost" @click="stockOpen = false">Отмена</UButton><UButton type="submit" :loading="pending">Списать</UButton></div></form></template></USlideover>

    <USlideover v-model:open="completeOpen" title="Завершить работу"><template #body><form v-if="selected" class="form-grid" @submit.prevent="complete"><section v-if="selected.checklist.length"><p class="mb-2 font-semibold">Чек-лист</p><label v-for="item in selected.checklist" :key="item.label" class="flex min-h-11 items-center gap-3"><input v-model="item.checked" type="checkbox">{{ item.label }}</label></section><UFormField label="Комментарий"><UTextarea v-model="comment" /></UFormField><label class="flex min-h-11 items-center gap-3 font-medium"><input v-model="hasProblem" type="checkbox">Есть проблема</label><UFormField v-if="hasProblem" label="Описание проблемы"><UTextarea v-model="problemDescription" required /></UFormField><UFormField label="Фото" help="Необязательно"><UInput type="file" accept="image/*" @change="selectPhoto" /></UFormField><UAlert v-if="error" color="error" variant="soft" :description="error" /><div class="form-actions"><UButton color="neutral" variant="ghost" @click="completeOpen = false">Отмена</UButton><UButton type="submit" :loading="pending">Подтвердить завершение</UButton></div></form></template></USlideover>
  </section>
</template>
